services:
    client:
        container_name: streamlit_demo
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        image: streamlit_demo
        pull_policy: build
        # env_file: .env
        volumes:
            - ./data:/usr/src/app/data
        ports:
            - 8501:8501
